parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json
  sourceType: module
settings:
  'import/resolver':
    typescript:
      alwaysTryTypes: true
env:
  node: true
  jest: true
plugins:
  - '@typescript-eslint'
  - import
extends:
  - '@herp-inc'
  - prettier
rules:
  yoda: [error, always, { onlyEquality: true, exceptRange: true }]
  complexity: [error, 20]
  prefer-arrow-callback: error
  arrow-body-style: [error, as-needed]
  no-console: off
  no-negated-condition: off
  import/no-default-export: off
  '@typescript-eslint/array-type': ['error', { default: 'array' }]
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/no-var-requires': off
  '@typescript-eslint/strict-boolean-expressions': off
  '@typescript-eslint/prefer-nullish-coalescing': off
  '@typescript-eslint/consistent-type-imports':
    [error, { fixStyle: separate-type-imports }]
overrides:
  - files: ['*.ts', '*.tsx']
    rules:
      '@typescript-eslint/no-var-requires': error
